package cn.zx.ghjmaven.domain;
// Generated 2017-8-25 15:14:53 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer",schema="zhongxi")
public class Customer  implements java.io.Serializable {

     private Integer cid;
     private String cname;
     private String caddress;
     private String clinkman;
     private String ctelephone;
     private String citem;

    public Customer() {
    }

    public Customer(Integer cid,String cname, String caddress, String clinkman, String ctelephone, String citem) {
       this.cid = cid;
       this.cname = cname;
       this.caddress = caddress;
       this.clinkman = clinkman;
       this.ctelephone = ctelephone;
       this.citem = citem;
    }
   
    @Id
//    @GenericGenerator(name="generator",strategy="uuid")
//	@GeneratedValue(generator="generator")
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="cid", unique=true, nullable=false)
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    
    @Column(name="cname", length=32)
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }
    
    @Column(name="caddress", length=32)
    public String getCaddress() {
        return this.caddress;
    }
    
    public void setCaddress(String caddress) {
        this.caddress = caddress;
    }
    
    @Column(name="clinkman", length=32)
    public String getClinkman() {
        return this.clinkman;
    }
    
    public void setClinkman(String clinkman) {
        this.clinkman = clinkman;
    }
    
    @Column(name="ctelephone", length=32)
    public String getCtelephone() {
        return this.ctelephone;
    }
    
    public void setCtelephone(String ctelephone) {
        this.ctelephone = ctelephone;
    }
    
    @Column(name="citem", length=32)
    public String getCitem() {
        return this.citem;
    }
    
    public void setCitem(String citem) {
        this.citem = citem;
    }

	@Override
	public String toString() {
		return "Customer [cid=" + cid + ", cname=" + cname + ", caddress="
				+ caddress + ", clinkman=" + clinkman + ", ctelephone="
				+ ctelephone + ", citem=" + citem + "]";
	}




}


