package cn.zx.ghjmaven.domain;
// Generated 2017-8-26 17:23:07 by Hibernate Tools 3.2.2.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.io.File;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Itemer generated by hbm2java
 * 项目
 */
@Entity
@Table(name="itemer",schema="zhongxi")
public class Itemer  implements java.io.Serializable {

     private Integer iid;
     private String iname;
     private Date istartdate;
     private Date ienddate;
     private String imanager;
     private String imember;
     private Integer status;
//     private List<File> file;
//     private List<String> fileName;
//     private List<String> fileType;
	 private String file;
	 private String fileName;
	 private String fileType;
     private Integer id;
     private Integer cid;

    public Itemer() {
    }

    public Itemer(Integer iid, String iname, Date istartdate, Date ienddate,
			String imanager, String imember, Integer status, String file,
			String fileName, String fileType, Integer id,
			Integer cid) {
		super();
		this.iid = iid;
		this.iname = iname;
		this.istartdate = istartdate;
		this.ienddate = ienddate;
		this.imanager = imanager;
		this.imember = imember;
		this.status = status;
		this.file = file;
		this.fileName = fileName;
		this.fileType = fileType;
		this.id = id;
		this.cid = cid;
	}

    @Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="iid", unique=true, nullable=false)
    public Integer getIid() {
        return this.iid;
    }
    
    public void setIid(Integer iid) {
        this.iid = iid;
    }
    
    @Column(name="iname", length=32)
    public String getIname() {
        return this.iname;
    }
    
    public void setIname(String iname) {
        this.iname = iname;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="istartdate")
    public Date getIstartdate() {
		return istartdate;
	}

	public void setIstartdate(Date istartdate) {
		this.istartdate = istartdate;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="ienddate")
	public Date getIenddate() {
		return ienddate;
	}

	public void setIenddate(Date ienddate) {
		this.ienddate = ienddate;
	}

	@Column(name="imanager", nullable=false, length=32)
    public String getImanager() {
        return this.imanager;
    }
    
    public void setImanager(String imanager) {
        this.imanager = imanager;
    }
    
    @Column(name="imember", nullable=false, length=32)
    public String getImember() {
        return this.imember;
    }
    
    public void setImember(String imember) {
        this.imember = imember;
    }
    @Column(name="status", length=10)
    public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name="file")
    public String getFile() {
		return file;
	}

	public void setFile(String file) {
		this.file = file;
	}
	@Column(name="fileName")
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	@Column(name="fileType")
	public String getFileType() {
		return fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="cid", nullable=false)
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }

	@Override
	public String toString() {
		return "Itemer [iid=" + iid + ", iname=" + iname + ", istartdate="
				+ istartdate + ", ienddate=" + ienddate + ", imanager="
				+ imanager + ", imember=" + imember + ", status=" + status
				+ ", file=" + file + ", fileName=" + fileName + ", fileType="
				+ fileType + ", id=" + id + ", cid=" + cid + "]";
	}

}


